{
 "title": "Performance",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "channel", "label": "channel", "query": "ledger_transaction_count" },
   { "name": "span", "query": "15s" },
   {
    "name": "container",
    "query": "container_cpu_usage_seconds_total{container_label_org_hyperledger_fabric_version!=\"\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Transcations per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Transactions per second" }
   ],
   "targets": [
    {
     "expr": "irate(ledger_transaction_count{channel=\"$channel\",chaincode!=\"unknown\"}[$span])",
     "legendFormat": "{{chaincode}} ({{ validation_code }})"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "idelta(ledger_blockstorage_commit_time_sum{channel=\"$channel\"}[$span])/idelta(ledger_blockstorage_commit_time_count{channel=\"$channel\"}[$span])",
     "legendFormat": "block_commit"
    },
    {
     "expr": "idelta(ledger_block_processing_time_sum{channel=\"$channel\"}[$span])/idelta(ledger_block_processing_time_count{channel=\"$channel\"}[$span])",
     "legendFormat": "state_validation"
    },
    {
     "expr": "idelta(ledger_statedb_commit_time_sum{channel=\"$channel\"}[$span])/idelta(ledger_statedb_commit_time_count{channel=\"$channel\"}[$span])",
     "legendFormat": "state_commit"
    },
    {
     "expr": "idelta(blockcutter_block_fill_duration_sum{channel=\"$channel\"}[$span])/idelta(blockcutter_block_fill_duration_count{channel=\"$channel\"}[$span])",
     "legendFormat": "block_fill"
    }
   ]
  },
  {
   "title": "CPU ($container)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "repeat": "container",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_system_seconds_total{name=~\"$container\"}[$span]))",
     "legendFormat": "System"
    },
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{name=~\"$container\"}[$span]))",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "Memory ($container)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "repeat": "container",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=~\"$container\"}",
     "legendFormat": "working_set_bytes"
    },
    {
     "expr": "container_memory_usage_bytes{name=~\"$container\"}",
     "legendFormat": "usage_bytes "
    },
    {
     "expr": "container_memory_rss{name=~\"$container\"}",
     "legendFormat": "rss"
    },
    {
     "expr": "container_memory_swap{name=~\"$container\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "container_memory_cache{name=~\"$container\"}",
     "legendFormat": "cache"
    }
   ]
  },
  {
   "title": "CPU ($container)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_system_seconds_total{name=~\"$container\"}[$span]))",
     "legendFormat": "System"
    },
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{name=~\"$container\"}[$span]))",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "Memory ($container)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=~\"$container\"}",
     "legendFormat": "working_set_bytes"
    },
    {
     "expr": "container_memory_usage_bytes{name=~\"$container\"}",
     "legendFormat": "usage_bytes "
    },
    {
     "expr": "container_memory_rss{name=~\"$container\"}",
     "legendFormat": "rss"
    },
    {
     "expr": "container_memory_swap{name=~\"$container\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "container_memory_cache{name=~\"$container\"}",
     "legendFormat": "cache"
    }
   ]
  },
  {
   "title": "CPU ($container)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_system_seconds_total{name=~\"$container\"}[$span]))",
     "legendFormat": "System"
    },
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{name=~\"$container\"}[$span]))",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "Memory ($container)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=~\"$container\"}",
     "legendFormat": "working_set_bytes"
    },
    {
     "expr": "container_memory_usage_bytes{name=~\"$container\"}",
     "legendFormat": "usage_bytes "
    },
    {
     "expr": "container_memory_rss{name=~\"$container\"}",
     "legendFormat": "rss"
    },
    {
     "expr": "container_memory_swap{name=~\"$container\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "container_memory_cache{name=~\"$container\"}",
     "legendFormat": "cache"
    }
   ]
  },
  {
   "title": "Disk I/O Bytes ($container)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "repeat": "container",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{name=~\"$container\"}[$span])) by (device)",
     "legendFormat": "read ({{device}})"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{name=~\"$container\"}[$span])) by (device)",
     "legendFormat": "write ({{device}})"
    }
   ]
  },
  {
   "title": "Disk I/O Ops ($container)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "repeat": "container",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_total{name=~\"$container\"}[$span])) by (device)",
     "legendFormat": "reads ({{ device }})"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{name=~\"$container\"}[$span])) by (device)",
     "legendFormat": "write ({{ device }})"
    }
   ]
  },
  {
   "title": "Disk I/O Bytes ($container)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{name=~\"$container\"}[$span])) by (device)",
     "legendFormat": "read ({{device}})"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{name=~\"$container\"}[$span])) by (device)",
     "legendFormat": "write ({{device}})"
    }
   ]
  },
  {
   "title": "Disk I/O Ops ($container)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_total{name=~\"$container\"}[$span])) by (device)",
     "legendFormat": "reads ({{ device }})"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{name=~\"$container\"}[$span])) by (device)",
     "legendFormat": "write ({{ device }})"
    }
   ]
  },
  {
   "title": "Disk I/O Bytes ($container)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{name=~\"$container\"}[$span])) by (device)",
     "legendFormat": "read ({{device}})"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{name=~\"$container\"}[$span])) by (device)",
     "legendFormat": "write ({{device}})"
    }
   ]
  },
  {
   "title": "Disk I/O Ops ($container)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_total{name=~\"$container\"}[$span])) by (device)",
     "legendFormat": "reads ({{ device }})"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{name=~\"$container\"}[$span])) by (device)",
     "legendFormat": "write ({{ device }})"
    }
   ]
  },
  {
   "title": "Network throughput in bytes ($container)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "repeat": "container",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{name=~\"$container\"}[$span])",
     "legendFormat": "inbound ({{ interface }})"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{name=~\"$container\"}[$span])",
     "legendFormat": "outbound ({{ interface }})"
    }
   ]
  },
  {
   "title": "Network throughputs in packets ($container)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "repeat": "container",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_packets_total{name=~\"$container\"}[$span])",
     "legendFormat": "inbound ({{ interface }})"
    },
    {
     "expr": "irate(container_network_transmit_packets_total{name=~\"$container\"}[$span])",
     "legendFormat": "outbound ({{ interface }})"
    }
   ]
  },
  {
   "title": "Network throughput in bytes ($container)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{name=~\"$container\"}[$span])",
     "legendFormat": "inbound ({{ interface }})"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{name=~\"$container\"}[$span])",
     "legendFormat": "outbound ({{ interface }})"
    }
   ]
  },
  {
   "title": "Network throughputs in packets ($container)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_packets_total{name=~\"$container\"}[$span])",
     "legendFormat": "inbound ({{ interface }})"
    },
    {
     "expr": "irate(container_network_transmit_packets_total{name=~\"$container\"}[$span])",
     "legendFormat": "outbound ({{ interface }})"
    }
   ]
  },
  {
   "title": "Network throughput in bytes ($container)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{name=~\"$container\"}[$span])",
     "legendFormat": "inbound ({{ interface }})"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{name=~\"$container\"}[$span])",
     "legendFormat": "outbound ({{ interface }})"
    }
   ]
  },
  {
   "title": "Network throughputs in packets ($container)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_packets_total{name=~\"$container\"}[$span])",
     "legendFormat": "inbound ({{ interface }})"
    },
    {
     "expr": "irate(container_network_transmit_packets_total{name=~\"$container\"}[$span])",
     "legendFormat": "outbound ({{ interface }})"
    }
   ]
  }
 ]
}