{
 "title": "Fabric",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "channel", "label": "Channel", "query": "ledger_transaction_count" },
   {
    "name": "container",
    "label": "Container",
    "query": "container_cpu_usage_seconds_total{container_label_org_hyperledger_fabric_version!=\"\"}"
   },
   { "name": "span", "query": "15s" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_uname_info{instance=~\"$node\"},nodename)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_cpu_seconds_total,instance)"
   }
  ]
 },
 "panels": [
  { "title": "Host ($host)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1-avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$span]))"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": " 1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes"
    }
   ]
  },
  {
   "title": "CPU(s)",
   "type": "singlestat",
   "description": "Logical processors (hardware threads)",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "machine_memory_bytes" }
   ]
  },
  { "title": "Fabric ($channel)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "channel" },
  {
   "title": "Transcations per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Transactions per second" }
   ],
   "targets": [
    {
     "expr": "irate(ledger_transaction_count{channel=\"$channel\",chaincode!=\"unknown\"}[$span])",
     "legendFormat": "{{chaincode}} ({{ validation_code }})"
    }
   ]
  },
  {
   "title": "Blocks per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ledger_blockchain_height{channel=~\"$channel\"}[$span])",
     "legendFormat": "blocks ({{ $instance }})"
    }
   ]
  },
  {
   "title": "Chaincode shim operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "operations per second" }
   ],
   "targets": [
    {
     "expr": "irate(chaincode_shim_requests_received{channel=~\"$channel\"}[$span])",
     "legendFormat": "{{ type }} recieved ({{ instance }})"
    },
    {
     "expr": "irate(chaincode_shim_requests_completed{channel=~\"$channel\"}[$span])",
     "legendFormat": "{{ type }} completed ({{ instance }})"
    }
   ]
  },
  {
   "title": "Chaincode shim latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(chaincode_shim_request_duration_sum{channel=~\"$channel\"}[$span])/irate(chaincode_shim_request_duration_count{channel=~\"$channel\"}[$span])",
     "legendFormat": "{{ type }}/{{ success }} ({{ chaincode }} {{ instance }})"
    }
   ]
  },
  {
   "title": "Orderer Transaction Throughputs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(broadcast_processed_count{channel=~\"$channel\"}[$span])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Orderer Transaction Latencies (stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(broadcast_validate_duration_sum{channel=~\"$channel\",type=\"ENDORSER_TRANSACTION\"}[$span]))/sum(irate(broadcast_validate_duration_count{channel=~\"$channel\",type=\"ENDORSER_TRANSACTION\"}[$span]))",
     "legendFormat": "validate"
    },
    {
     "expr": "sum(irate(broadcast_enqueue_duration_sum{channel=~\"$channel\",type=\"ENDORSER_TRANSACTION\"}[$span]))/sum(irate(broadcast_enqueue_duration_count{channel=~\"$channel\",type=\"ENDORSER_TRANSACTION\"}[$span]))",
     "legendFormat": "enqueue"
    }
   ]
  },
  {
   "title": "Orderer Block Latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "idelta(blockcutter_block_fill_duration_sum{channel=~\"$channel\"}[$span])/idelta(blockcutter_block_fill_duration_count{channel=~\"$channel\"}[$span])",
     "legendFormat": "block_fill"
    }
   ]
  },
  {
   "title": "Orderer Deliver Blocks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(deliver_blocks_sent{channel=~\"$channel\",instance=~\"orderer.*\"}[$span])",
     "legendFormat": "blocks_sent ({{ instance }}, filtered:{{ filtered }})"
    },
    {
     "expr": "irate(deliver_requests_received{channel=~\"$channel\",instance=~\"orderer.*\"}[$span])",
     "legendFormat": "requests_received  ({{ instance }}, filtered:{{ filtered }})"
    },
    {
     "expr": "irate(deliver_requests_completed{channel=~\"$channel\",instance=~\"orderer.*\"}[$span])",
     "legendFormat": "requests_completed  ({{ instance }}, filtered:{{ filtered }})"
    },
    {
     "expr": "irate(deliver_streams_opened{instance=~\"orderer.*\"}[$span])",
     "legendFormat": "streams_opened  ({{ instance }})"
    },
    {
     "expr": "irate(deliver_streams_closed{instance=~\"orderer.*\"}[$span])",
     "legendFormat": "streams_closed  ({{ instance }})"
    }
   ]
  },
  {
   "title": "Peer Latencies (stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "idelta(ledger_block_processing_time_sum{channel=~\"$channel\"}[$span])/idelta(ledger_block_processing_time_count{channel=~\"$channel\"}[$span])",
     "legendFormat": "state_validation"
    },
    {
     "expr": "idelta(ledger_blockstorage_commit_time_sum{channel=~\"$channel\"}[$span])/idelta(ledger_blockstorage_commit_time_count{channel=~\"$channel\"}[$span])",
     "legendFormat": "block_commit"
    },
    {
     "expr": "idelta(ledger_statedb_commit_time_sum{channel=~\"$channel\"}[$span])/idelta(ledger_statedb_commit_time_count{channel=~\"$channel\"}[$span])",
     "legendFormat": "state_commit"
    }
   ]
  },
  {
   "title": "EventHub",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(deliver_blocks_sent{channel=~\"$channel\",instance=~\"peer.*\"}[$span])",
     "legendFormat": "blocks_sent ({{ instance }}, filtered:{{ filtered }})"
    },
    {
     "expr": "irate(deliver_requests_received{channel=~\"$channel\",instance=~\"peer.*\"}[$span])",
     "legendFormat": "requests_received  ({{ instance }}, filtered:{{ filtered }})"
    },
    {
     "expr": "irate(deliver_requests_completed{channel=~\"$channel\",instance=~\"peer.*\"}[$span])",
     "legendFormat": "requests_completed  ({{ instance }}, filtered:{{ filtered }})"
    },
    {
     "expr": "irate(deliver_streams_opened{instance=~\"peer.*\"}[$span])",
     "legendFormat": "streams_opened  ({{ instance }})"
    },
    {
     "expr": "irate(deliver_streams_closed{instance=~\"peer.*\"}[$span])",
     "legendFormat": "streams_closed  ({{ instance }})"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{container_label_org_hyperledger_fabric_version!=\"\"}[$span])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}