{
 "title": "Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "channel", "label": "Channel", "query": "ledger_transaction_count" },
   {
    "name": "orderer",
    "label": "Orderer",
    "query": "blockcutter_block_fill_duration_count"
   },
   { "name": "peer", "label": "Peer", "query": "ledger_transaction_count" },
   {
    "name": "container",
    "label": "Container",
    "query": "container_cpu_usage_seconds_total{container_label_org_hyperledger_fabric_version!=\"\"}"
   },
   { "name": "span", "query": "15s" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_uname_info{instance=~\"$node\"},nodename)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_cpu_seconds_total,instance)"
   }
  ]
 },
 "panels": [
  { "title": "Host ($host)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1-avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$span]))"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": " 1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes"
    }
   ]
  },
  {
   "title": "CPU(s)",
   "type": "singlestat",
   "description": "Logical processors (hardware threads)",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "machine_memory_bytes" }
   ]
  },
  { "title": "Fabric ($channel)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "channel" },
  {
   "title": "Transcations per second [$peer]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Transactions per second" }
   ],
   "targets": [
    {
     "expr": "irate(ledger_transaction_count{channel=\"$channel\",instance=~\"$peer:.*\",chaincode!=\"unknown\"}[$span])",
     "legendFormat": "{{chaincode}} ({{ validation_code }})"
    }
   ]
  },
  {
   "title": "Blocks per second [$peer]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ledger_blockchain_height{channel=~\"$channel\",instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Endorser proposals ($peer)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Proposals per second" }
   ],
   "targets": [
    {
     "expr": "irate(endorser_proposals_received{instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "Received"
    },
    {
     "expr": "irate(endorser_successful_proposals{instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "Succeeded"
    }
   ]
  },
  {
   "title": "Endorser proposal latencies ($peer)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(endorser_propsal_duration_sum{instance=~\"$peer:.*\",channel=~\"$channel\"}[$span])/irate(endorser_propsal_duration_count{instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "{{ chaincode }}"
    },
    {
     "expr": "irate(endorser_propsal_duration_sum{instance=~\"$peer:.*\",channel=\"\"}[$span])/irate(endorser_propsal_duration_count{instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "{{ chaincode }}"
    }
   ]
  },
  {
   "title": "Chaincode shim operations [$peer]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "operations per second" }
   ],
   "targets": [
    {
     "expr": "irate(chaincode_shim_requests_received{channel=~\"$channel\",instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "{{ type }} recieved ({{ chaincode }})"
    },
    {
     "expr": "irate(chaincode_shim_requests_received{channel=\"\",instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "{{ type }} recieved ({{ chaincode }})"
    },
    {
     "expr": "irate(chaincode_shim_requests_completed{channel=~\"$channel\",instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "{{ type }} completed ({{ chaincode }})"
    },
    {
     "expr": "irate(chaincode_shim_requests_completed{channel=\"\",instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "{{ type }} completed ({{ chaincode }})"
    }
   ]
  },
  {
   "title": "Chaincode shim latencies [$peer]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(chaincode_shim_request_duration_sum{channel=~\"$channel\",instance=~\"$peer:.*\"}[$span])/irate(chaincode_shim_request_duration_count{channel=~\"$channel\",instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "{{ type }}/{{ success }} ({{ chaincode }})"
    },
    {
     "expr": "irate(chaincode_shim_request_duration_sum{channel=\"\",instance=~\"$peer:.*\"}[$span])/irate(chaincode_shim_request_duration_count{channel=\"\",instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "{{ type }}/{{ success }} ({{ chaincode }})"
    }
   ]
  },
  {
   "title": "Orderer Transaction Throughputs [$orderer]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Transactions per second" }
   ],
   "targets": [
    {
     "expr": "sum(irate(broadcast_processed_count{channel=~\"$channel\",instance=~\"$orderer:.*\"}[$span])) by (instance)",
     "legendFormat": "transaction"
    }
   ]
  },
  {
   "title": "Orderer Transaction Latencies (stacked) [$orderer]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(broadcast_validate_duration_sum{channel=~\"$channel\",instance=~\"$orderer:.*\",type=\"ENDORSER_TRANSACTION\"}[$span]))/sum(irate(broadcast_validate_duration_count{channel=~\"$channel\",type=\"ENDORSER_TRANSACTION\"}[$span]))",
     "legendFormat": "validate"
    },
    {
     "expr": "sum(irate(broadcast_enqueue_duration_sum{channel=~\"$channel\",instance=~\"$orderer:.*\",type=\"ENDORSER_TRANSACTION\"}[$span]))/sum(irate(broadcast_enqueue_duration_count{channel=~\"$channel\",type=\"ENDORSER_TRANSACTION\"}[$span]))",
     "legendFormat": "enqueue"
    }
   ]
  },
  {
   "title": "Orderer Block Latencies [$orderer]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "idelta(blockcutter_block_fill_duration_sum{channel=~\"$channel\",instance=~\"$orderer:.*\"}[$span])/idelta(blockcutter_block_fill_duration_count{channel=~\"$channel\",instance=~\"$orderer:.*\"}[$span])",
     "legendFormat": "block_fill"
    }
   ]
  },
  {
   "title": "Orderer Deliver Blocks [$orderer]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "Blocks per second" }
   ],
   "targets": [
    {
     "expr": "irate(deliver_blocks_sent{channel=~\"$channel\",instance=~\"$orderer:.*\"}[$span])",
     "legendFormat": "blocks_sent (filtered:{{ filtered }})"
    },
    {
     "expr": "irate(deliver_requests_received{channel=~\"$channel\",instance=~\"$orderer:.*\"}[$span])",
     "legendFormat": "requests_received  (filtered:{{ filtered }})"
    },
    {
     "expr": "irate(deliver_requests_completed{channel=~\"$channel\",instance=~\"$orderer:.*\"}[$span])",
     "legendFormat": "requests_completed  (filtered:{{ filtered }})"
    },
    {
     "expr": "irate(deliver_streams_opened{instance=~\"$orderer:.*\"}[$span])",
     "legendFormat": "streams_opened"
    },
    {
     "expr": "irate(deliver_streams_closed{instance=~\"$orderer:.*\"}[$span])",
     "legendFormat": "streams_closed"
    }
   ]
  },
  {
   "title": "Peer Latencies (stacked) [$peer]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "idelta(ledger_block_processing_time_sum{channel=~\"$channel\",instance=~\"$peer:.*\"}[$span])/idelta(ledger_block_processing_time_count{channel=~\"$channel\",instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "state_validation"
    },
    {
     "expr": "idelta(ledger_blockstorage_commit_time_sum{channel=~\"$channel\",instance=~\"$peer:.*\"}[$span])/idelta(ledger_blockstorage_commit_time_count{channel=~\"$channel\",instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "block_commit"
    },
    {
     "expr": "idelta(ledger_statedb_commit_time_sum{channel=~\"$channel\",instance=~\"$peer:.*\"}[$span])/idelta(ledger_statedb_commit_time_count{channel=~\"$channel\",instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "state_commit"
    }
   ]
  },
  {
   "title": "EventHub [$peer]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short", "label": "Operations per second" }
   ],
   "targets": [
    {
     "expr": "irate(deliver_blocks_sent{channel=~\"$channel\",instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "blocks_sent (filtered:{{ filtered }})"
    },
    {
     "expr": "irate(deliver_requests_received{channel=~\"$channel\",instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "requests_received  (filtered:{{ filtered }})"
    },
    {
     "expr": "irate(deliver_requests_completed{channel=~\"$channel\",instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "requests_completed  (filtered:{{ filtered }})"
    },
    {
     "expr": "irate(deliver_streams_opened{instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "streams_opened"
    },
    {
     "expr": "irate(deliver_streams_closed{instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "streams_closed"
    }
   ]
  },
  {
   "title": "Gossip messages ($peer)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short", "label": "Messages per second" }
   ],
   "targets": [
    {
     "expr": "irate(gossip_comm_messages_received{instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "received"
    },
    {
     "expr": "irate(gossip_comm_messages_sent{instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Gossip state commit latencies ($peer)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(gossip_state_commit_duration_sum{instance=~\"$peer:.*\"}[$span])/irate(gossip_state_commit_duration_count{instance=~\"$peer:.*\"}[$span])",
     "legendFormat": "block commit"
    }
   ]
  },
  {
   "title": "Gossip payload buffer size ($peer)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "gossip_payload_buffer_size{instance=~\"$peer:.*\"}",
     "legendFormat": "payload buffer"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 441 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 442 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{container_label_ccperf_container_type=\"sut\"}[$span])) by (name)",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{container_label_org_hyperledger_fabric_chaincode_id_version!=\"\"}[$span])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}